server:
  port: 8282
  ssl:
    enabled: false
    keyStoreType: JKS
    key-alias: selfsigned
    key-store: /etc/ssl/certs/belgiantrain.jks
    key-store-password: password

spring:
  cloud:
    config:
      server:
        git:
          uri: file:./config

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8446/eureka}