server:
  port: 8282

spring:
  cloud:
    config:
      server:
        git:
          uri: file:./config

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8283/eureka}